server:
  servlet:
    context-path: /
    session:
      persistent: true
  port: 8080
  error:
    whitelabel:
      enabled: true

spring:
  profiles:
    active: dev

app: 
  business_id : 1000010101
  division : 01
  shop : 01
  counter : 01
