server:
  servlet:
    context-path: /
    session:
      persistent: true
  port: 8080
  error:
    whitelabel:
      enabled: true

spring:
  profiles:
    active: dev

app: 
  business_id : 1000101010
  division : 10
  shop : 10
  counter : 10
  max-shift: 3
  active-inventory: true
