server:
  servlet:
    context-path: /
    session:
      persistent: true
  port: 8081
  error:
    whitelabel:
      enabled: true

spring:
  profiles:
    active: dev

app: 
  business_id : 10000101
  division : 01
  shop : 01
  counter : 01
  max-shift: 3
  active-inventory: true
